on:
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - uses: actions/checkout@v6
      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: install depencies
        run: pnpm install --frozen-lockfile
      - name: build application for cloudflare workers
        run: pnpm build
      - name: Build and Deploy
        uses: cloudflare/wrangler-action@v3.15.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy
