on:
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - uses: actions/checkout@v6
      - name: Deploy to Cloudflare Workers with Wrangler
        id: deploy
        uses: cloudflare/wrangler-action@v3.15.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerConfigPath: ./wrangler.jsonc
      - name: print pages-deployment-alias-url
        run: echo ${{ steps.deploy.outputs.deployment-url }}
