on:
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "25"
      - run: pnpm add -g wrangler
      - run: ls -la
      - run: pnpm install
      - run: pnpm build
      - run: wrangler deploy --config ./dist/server/wrangler.json --name "citadel-${{ github.ref_name }}"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
